### ISSUE TITLE
[Question] useListenable() in flutter_hooks is supported?

### ISSUE THREAD

**Issue by chunghha** [SchabanBo/qlevar_router#31]
I am converting the example with useListenable in flutter_hooks.

```
class HomePage extends HookWidget {
  final QRouter _router;

  const HomePage(this._router, {Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final _navi = useListenable(_router.navigator);
    // ignore: avoid_print
    print(_navi.currentRoute.name);

    return Scaffold(
      appBar: AppBar(
        title: Text('My App'),
        centerTitle: true,
        actions: [
          IconButton(
            onPressed: () {
              AuthState.isAuthed = false;
              QR.navigator.replaceAll('/login');
            },
            icon: Icon(Icons.logout),
          )
        ],
      ),
      body: _router,
      bottomNavigationBar: BottomNavigationBar(
        items: const [
          BottomNavigationBarItem(icon: Icon(Icons.home), label: 'home'),
          BottomNavigationBarItem(icon: Icon(Icons.store), label: 'store'),
          BottomNavigationBarItem(
            icon: Icon(Icons.settings),
            label: 'Settings',
          )
        ],
        currentIndex: AppRouter.tabs
            .indexWhere((element) => element == _router.routeName),
        onTap: (v) => QR.toName(AppRouter.tabs[v]),
      ),
    );
  }
```

And, facing this exception on logout.

```
flutter: QR: Finding Match for /login under root
flutter: QR: Navigator with name [/home] was removed
flutter: QR: adding Route: Key: [0](/login), Full Path: /login to the navigator with Key: [-1](Root)

══╡ EXCEPTION CAUGHT BY HOOKS LIBRARY ╞═════════════════════════════════════════════════════════════
The following assertion was thrown while disposing _Entry<HookState<dynamic, Hook<dynamic>>>:
A QRouterController was used after being disposed.
Once you have called dispose() on a QRouterController, it can no longer be used.

When the exception was thrown, this was the stack:
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:114:9)
#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:120:6)
#2      ChangeNotifier.removeListener (package:flutter/src/foundation/change_notifier.dart:233:12)
#3      _ListenableStateHook.dispose (package:flutter_hooks/src/listenable.dart:75:21)
(SNIP)
#125    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
#126    _drawFrame (dart:ui/hooks.dart:127:31)
(elided 3 frames from dart:async)
```

Functionally this app (https://github.com/chunghha/fl_router_poc) works with HookWidget even if the exception above occurs including re-login.

@SchabanBo  could you take a look further? I think the exception is related to this line of code "**QR.navigator.replaceAll('/login');**". However, I am not sure about where between my code, this package or flutter_hooks to fix. If you'd give an insight, that would be a help.

**Comment by chunghha** [comment]
I could resolve the exception by replacing useListenable() with useValueNotifier() so close this.
