### ISSUE TITLE
Is there any way to reset or recover from a 'Bad state: No element' error?

### ISSUE THREAD

**Issue by bobwiller** [SchabanBo/qlevar_router#67]
In our app, we have a login screen that allows the user to select a settings screen where they can change their language/locale.  When they hit save, it (essentially) reloads the app using the Phoenix package. When the MaterialApp rebuilds, we can no longer navigate in code as the QR.navigator and QR.rootNavigator both have the following error:
<Bad state: No element
#0      ListMixin.firstWhere (dart:collection/list.dart:167:5)
#1      ControllerManager.withName (package:qlevar_router/src/controllers/controller_manager.dart:49:19)
#2      QRContext.navigatorOf (package:qlevar_router/src/qr.dart:56:51)
#3      QRContext.navigator (package:qlevar_router/src/qr.dart:53:31)
#4      QRContext.Eval ()
#5      QRContext.Eval ()
#6      QRContext.Eval ()
...

Not sure what causes this error or if there is any way to recover from it?

**Comment by SchabanBo** [comment]
I couldn't reproduce the problem!
I tried the fowling examples:

<details>
  <summary>Example 1</summary>

``` dart

void main()=> Phoenix(child:App());

class App extends StatelessWidget {
  const App({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routeInformationParser: const QRouteInformationParser(),
      routerDelegate: QRouterDelegate(
        [
          QRoute(
            path: '/login',
            builder: () => ElevatedButton(
              onPressed: () => QR.to('/settings'),
              child: const Text('settings'),
            ),
          ),
          QRoute(
            path: '/settings',
            builder: () => ElevatedButton(
              onPressed: () {
                Phoenix.rebirth(context);
              },
              child: const Text('reset'),
            ),
          ),
        ],
        initPath: '/login',
      ),
    );
  }
}

```
</details>

<details>
  <summary>Example 2</summary>
  
```dart
void main() {
  runApp(const Phoenix());
}

class Phoenix extends StatefulWidget {
  const Phoenix({Key? key}) : super(key: key);

  @override
  State<Phoenix> createState() => _PhoenixState();
}

class _PhoenixState extends State<Phoenix> {
  @override
  Widget build(BuildContext context) {
    return Container(
      key: UniqueKey(),
      child: MaterialApp.router(
        routeInformationParser: const QRouteInformationParser(),
        routerDelegate: QRouterDelegate(
          [
            QRoute(
              path: '/login',
              builder: () => TextButton(
                onPressed: () => QR.to('/settings'),
                child: const Text('settings'),
              ),
            ),
            QRoute(
              path: '/settings',
              builder: () => TextButton(
                onPressed: () {
                  setState(() {});
                  //  QR.to('/login');
                },
                child: const Text('reset'),
              ),
            ),
          ],
          initPath: '/login',
        ),
      ),
    );
  }
}
```
</details>

Can you share an example with the issue?
